routes/web.php
<?php

use App\Http\Controllers\BarTabletopGameController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TabletopGameController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/gamelist',BarTabletopGameController::class);

Auth::routes();


Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('roles', RoleController::class);

Route::resource('tabletopgames', TabletopGameController::class);

//// Routes for roles
////Index
//Route::get('/roles', [RoleController::class, 'index'])->name('roles.index');
//
////Create
//Route::get('/roles/create', [RoleController::class, 'create'])->name('roles.create');
////Show
//Route::get('/roles{role}', [RoleController::class, 'show'])->name('roles.show');
//
////Store
//Route::post('/roles/store', [RoleController::class, 'store'])->name('roles.store');
//
////Edit
//Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
//
////Update
//Route::patch('/roles/{role}', [RoleController::class, 'update'])->name('roles.update');
//
////Hard Delete
//Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->name('roles.destroy');

resources/views/ttg/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{route('roles.store')}}" method="post">
                    @csrf
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title">
                    <button type="submit">Add role</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/ttg/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{route('roles.update', $role->id)}}" method="post">
                    @csrf
                    @method('patch')
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" value="{{$role->title}}">
                    <button type="submit">Edit role</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/ttg/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    @foreach($bartabletopgames as $bartabletopgame)
                        <div class="card-header">
                           <a href="{{ route('gamelist.show', $bartabletopgame->id) }}">
                            <strong>{{ $bartabletopgame->title }}</strong></a>
                        </div>
                        <div class="card-body">  </div>
                        <div class="card-footer">
                        <a href="{{ route('gamelist.edit', $bartabletopgame->id) }}">Update</a>
                            <form action="{{ route('gamelist.destroy', $bartabletopgame->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit">Delete Game</button>
                            </form>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ttg/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <strong>{{ $bartabletopgame->title }}</strong><br>
                    </div>
                    <div class="card-body">
                        @foreach($bartabletopgames->bgg_id as $bartabletopgame)
                            {{ $bartabletopgame->name }} <br>
                        @endforeach

                    </div>
                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection